import { Check, Copy, Loader2, Sparkles } from 'lucide-react'
import { useState } from 'react'

import { Button } from '@/components/ui/button'
import { supabase } from '@/lib/supabase'

import type { BedConfig, RoomType } from '../steps/RoomsStep'

interface RoomDescriptionSuggestionsProps {
  room: Partial<RoomType>
  onSelect: (description: string) => void
}

/**
 * Room descriptions generated by a language model, with templates as the safety net.
 *
 * The generate-listing-copy edge function calls OpenAI (gpt-4o-mini, the provider and key this
 * project already uses in whatsapp-webhook) with the room's real attributes and returns three
 * variants.
 *
 * THE TEMPLATES BELOW ARE NOT DEAD CODE — they are the fallback. This endpoint can fail: no API
 * key configured, an OpenAI outage, a timeout, an unparseable response. A listing wizard that
 * dead-ends because a copywriting nicety is down would be a worse product than one with no AI at
 * all, so any non-200 quietly falls back to composed suggestions and the partner still gets
 * something usable. The UI says which one they are looking at rather than passing templates off as
 * generated text.
 */

const TYPE_OPENERS: Record<string, string[]> = {
  standard: [
    'A comfortable, well-appointed room with everything you need for a restful stay.',
    'Our classic room — simple, spotless and quietly comfortable.',
    'An easy, uncomplicated room that covers the essentials properly.',
  ],
  deluxe: [
    'A more generous room with elevated finishes and a little extra space to spread out.',
    'Thoughtfully upgraded throughout, with the details that make a stay feel considered.',
    'A step up in space and comfort, styled for guests who notice the difference.',
  ],
  suite: [
    'A separate living area and bedroom, giving you room to work, rest and entertain.',
    'A generously proportioned suite with distinct spaces for living and sleeping.',
    'Our suite offers the space of an apartment with the service of a hotel.',
  ],
  family: [
    'Built for families, with flexible bedding and space for everyone to settle in.',
    'A roomy, practical space designed around travelling with children.',
    'Plenty of room for the whole family, with bedding arranged for comfort at any age.',
  ],
  executive: [
    'Designed for business travel, with a proper workspace and a quiet setting.',
    'A calm, well-equipped room for guests who need to work as well as rest.',
    'Executive comfort with a dedicated desk, fast connectivity and an unhurried atmosphere.',
  ],
  presidential: [
    'Our finest accommodation — expansive, richly finished and thoughtfully serviced.',
    'The most spacious room we offer, appointed to the highest standard throughout.',
    'A landmark suite, with generous proportions and every detail carefully considered.',
  ],
}

const BED_WORDS: Record<BedConfig['type'], string> = {
  king: 'king bed',
  queen: 'queen bed',
  double: 'double bed',
  twin: 'twin bed',
  single: 'single bed',
  sofaBed: 'sofa bed',
}

function describeBeds(beds?: BedConfig[]): string {
  if (!beds || beds.length === 0) return ''
  const parts = beds
    .filter((b) => b.quantity > 0)
    .map((b) => {
      const word = BED_WORDS[b.type] ?? `${b.type} bed`
      return b.quantity > 1 ? `${b.quantity} ${word}s` : `a ${word}`
    })
  if (parts.length === 0) return ''
  if (parts.length === 1) return parts[0]
  return `${parts.slice(0, -1).join(', ')} and ${parts[parts.length - 1]}`
}

function buildSuggestions(room: Partial<RoomType>): string[] {
  const openers = TYPE_OPENERS[room.type ?? 'standard'] ?? TYPE_OPENERS.standard
  const beds = describeBeds(room.beds)
  const size = room.size && room.size > 0 ? `${room.size} m²` : ''
  const guests = room.maxGuests && room.maxGuests > 0 ? room.maxGuests : 0

  // Each suggestion = a type-appropriate opener + whatever concrete facts we actually have. Facts
  // are omitted rather than invented when the wizard has not collected them yet.
  return openers.map((opener) => {
    const facts: string[] = []
    if (size && beds) facts.push(`Spanning ${size}, it features ${beds}`)
    else if (size) facts.push(`It measures ${size}`)
    else if (beds) facts.push(`It features ${beds}`)

    if (guests) {
      facts.push(
        guests === 1
          ? 'and sleeps one guest comfortably'
          : `and sleeps up to ${guests} guests comfortably`,
      )
    }

    const detail = facts.length ? `${facts.join(' ')}.` : ''
    return [opener, detail].filter(Boolean).join(' ')
  })
}

export function RoomDescriptionSuggestions({ room, onSelect }: RoomDescriptionSuggestionsProps) {
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null)
  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [suggestions, setSuggestions] = useState<string[]>([])
  const [usedFallback, setUsedFallback] = useState(false)

  const generate = async () => {
    setLoading(true)
    try {
      const { data, error } = await supabase.functions.invoke('generate-listing-copy', {
        body: {
          kind: 'room',
          room: {
            type: room.type,
            name: room.name,
            beds: room.beds,
            size: room.size,
            maxGuests: room.maxGuests,
          },
        },
      })
      const generated: string[] = Array.isArray(data?.suggestions) ? data.suggestions : []
      if (error || generated.length === 0) throw error ?? new Error('no suggestions returned')
      setSuggestions(generated)
      setUsedFallback(false)
    } catch {
      // Never leave the partner with nothing — see the note at the top of this file.
      setSuggestions(buildSuggestions(room))
      setUsedFallback(true)
    } finally {
      setLoading(false)
    }
  }

  const handleToggle = () => {
    const next = !open
    setOpen(next)
    if (next && suggestions.length === 0) void generate()
  }

  return (
    <div className="mt-2">
      <Button
        type="button"
        variant="ghost"
        size="sm"
        onClick={handleToggle}
        disabled={loading}
        className="h-auto gap-1.5 px-2 py-1 text-xs text-primary hover:text-primary"
      >
        {loading ? (
          <Loader2 className="h-3.5 w-3.5 animate-spin" />
        ) : (
          <Sparkles className="h-3.5 w-3.5" />
        )}
        {loading ? 'Writing…' : open ? 'Hide suggestions' : 'Write a description for me'}
      </Button>

      {open && !loading && (
        <div className="mt-2 space-y-2">
          <div className="flex items-center justify-between gap-2">
            <p className="text-xs text-muted-foreground">
              {usedFallback
                ? 'Suggestions are unavailable right now, so these are written from your room’s type, beds and size.'
                : 'Written for this room from its type, beds and size. Edit freely — it’s a starting point.'}
            </p>
            <Button
              type="button"
              variant="ghost"
              size="sm"
              onClick={() => void generate()}
              className="h-auto shrink-0 px-2 py-1 text-xs"
            >
              Try again
            </Button>
          </div>
          {suggestions.map((text, i) => (
            <div
              key={i}
              className="rounded-lg border border-border bg-muted/30 p-3 text-sm text-foreground"
            >
              <p className="leading-relaxed">{text}</p>
              <div className="mt-2 flex gap-2">
                <Button
                  type="button"
                  size="sm"
                  variant="outline"
                  className="h-7 text-xs"
                  onClick={() => {
                    onSelect(text)
                    setCopiedIndex(i)
                    setTimeout(() => setCopiedIndex(null), 1500)
                  }}
                >
                  {copiedIndex === i ? (
                    <>
                      <Check className="mr-1 h-3 w-3" /> Added
                    </>
                  ) : (
                    <>
                      <Copy className="mr-1 h-3 w-3" /> Use this
                    </>
                  )}
                </Button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
