import { Anchor, Briefcase, Calendar, Crown, Flower, Globe, Heart, Landmark, Mountain, Users, Utensils } from 'lucide-react'

import { PackageType } from '../types'
import {
  AdventurePackageVector,
  BusinessEliteVector,
  CruiseWaterVector,
  CulinaryJourneyVector,
  CulturalHistoryVector,
  CustomPackageVector,
  EcoNatureVector,
  FamilyAdventureVector,
  LuxuryExperienceVector,
  RomanticEscapeVector,
  WeekendGetawayVector,
  WellnessRetreatVector,
} from './vectors'

export const PACKAGE_TYPE_CONFIG = {
  [PackageType.WEEKEND_GETAWAY]: {
    label: 'Weekend Getaway',
    description: 'Perfect for 2-3 day short trips',
    features: ['Flexible check-in', 'Late checkout', 'Weekend specials'],
    icon: Calendar,
    vector: WeekendGetawayVector,
    color: 'text-primary',
    bg: 'bg-primary/5',
    border: 'border-primary/20',
  },
  [PackageType.ROMANTIC_ESCAPE]: {
    label: 'Romantic Escape',
    description: 'Intimate packages for couples',
    features: ['Couples amenities', 'Private dining', 'Spa treatments'],
    icon: Heart,
    vector: RomanticEscapeVector,
    color: 'text-primary',
    bg: 'bg-primary/5',
    border: 'border-primary/20',
  },
  [PackageType.FAMILY_ADVENTURE]: {
    label: 'Family Adventure',
    description: 'Fun-filled packages for families',
    features: ['Kid-friendly activities', 'Family rooms', 'Entertainment'],
    icon: Users,
    vector: FamilyAdventureVector,
    color: 'text-primary',
    bg: 'bg-primary/5',
    border: 'border-primary/20',
  },
  [PackageType.BUSINESS_ELITE]: {
    label: 'Business Elite',
    description: 'Corporate rates and amenities',
    features: ['Meeting rooms', 'Business center', 'Express services'],
    icon: Briefcase,
    vector: BusinessEliteVector,
    color: 'text-primary',
    bg: 'bg-primary/5',
    border: 'border-primary/20',
  },
  [PackageType.ADVENTURE_PACKAGE]: {
    label: 'Adventure Package',
    description: 'Outdoor experiences and thrills',
    features: ['Outdoor activities', 'Equipment rental', 'Guided tours'],
    icon: Mountain,
    vector: AdventurePackageVector,
    color: 'text-primary',
    bg: 'bg-primary/5',
    border: 'border-primary/20',
  },
  [PackageType.CULINARY_JOURNEY]: {
    label: 'Culinary Journey',
    description: 'Gourmet dining experiences',
    features: ['Chef specials', 'Wine pairings', 'Cooking classes'],
    icon: Utensils,
    vector: CulinaryJourneyVector,
    color: 'text-primary',
    bg: 'bg-primary/5',
    border: 'border-primary/20',
  },
  [PackageType.WELLNESS_RETREAT]: {
    label: 'Wellness Retreat',
    description: 'Spa and wellness focused',
    features: ['Spa treatments', 'Yoga sessions', 'Healthy cuisine'],
    icon: Flower,
    vector: WellnessRetreatVector,
    color: 'text-primary',
    bg: 'bg-primary/5',
    border: 'border-primary/20',
  },
  [PackageType.LUXURY_EXPERIENCE]: {
    label: 'Luxury Experience',
    description: 'Ultra-premium VIP service',
    features: ['Concierge service', 'Premium amenities', 'Exclusive access'],
    icon: Crown,
    vector: LuxuryExperienceVector,
    color: 'text-primary',
    bg: 'bg-primary/5',
    border: 'border-primary/20',
  },
  [PackageType.CULTURAL_HISTORY]: {
    label: 'Cultural & History',
    description: 'Explore heritage and traditions',
    features: ['Museum passes', 'Guided heritage tours', 'Local workshops'],
    icon: Landmark,
    vector: CulturalHistoryVector,
    color: 'text-primary',
    bg: 'bg-primary/5',
    border: 'border-primary/20',
  },
  [PackageType.ECO_NATURE]: {
    label: 'Eco & Nature',
    description: 'Sustainable nature experiences',
    features: ['Wildlife watching', 'Eco-lodging', 'Conservation tours'],
    icon: Globe,
    vector: EcoNatureVector,
    color: 'text-primary',
    bg: 'bg-primary/5',
    border: 'border-primary/20',
  },
  [PackageType.CRUISE_WATER]: {
    label: 'Cruise & Water',
    description: 'Ocean and river adventures',
    features: ['Cabin upgrades', 'Shore excursions', 'Onboard credit'],
    icon: Anchor,
    vector: CruiseWaterVector,
    color: 'text-primary',
    bg: 'bg-primary/5',
    border: 'border-primary/20',
  },
  [PackageType.CUSTOM]: {
    label: 'Custom Package',
    description: 'Design your own package from scratch',
    features: ['Fully customizable', 'Your vision', 'Unlimited creativity'],
    icon: Briefcase, // Or Magic Wand if available? Briefcase is fine fallback.
    vector: CustomPackageVector,
    color: 'text-primary',
    bg: 'bg-primary/5',
    border: 'border-primary/20',
  },
}
