// Central Lucide re-exports. lucide-react-native v1 ships an `exports` map that
// blocks per-icon deep imports, so we re-export from the package barrel.
// Add a line here when you need a new icon; rename-map old names (e.g.
// BarChart3 → ChartColumn) so call sites stay stable.
export {
  Anchor,
  Bed,
  Bell,
  Briefcase,
  Building2,
  Bus,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  Castle,
  ChartColumn as BarChart3,
  Check,
  ChevronLeft,
  ChevronRight,
  Church,
  CircleAlert,
  CircleHelp,
  CircleUser,
  CircleX as XCircle,
  Clock,
  Coffee,
  Coins,
  Compass,
  ConciergeBell,
  CookingPot,
  CreditCard,
  Crown,
  Dumbbell,
  FileText,
  Flower2,
  Footprints,
  Gem,
  Gift,
  Globe,
  Heart,
  HeartPulse,
  Hotel,
  House,
  Landmark,
  LayoutDashboard,
  Lock,
  LogOut,
  Map,
  MapPin,
  Menu,
  MessageSquare,
  Minus,
  Mountain,
  Navigation,
  Pause,
  Percent,
  Plane,
  Plus,
  Receipt,
  Refrigerator,
  RefreshCcw,
  Search,
  SearchX,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Snowflake,
  Sparkles,
  Star,
  Ticket,
  TreePine,
  Tv,
  Umbrella,
  User,
  UserCheck,
  Users,
  Utensils,
  Wallet,
  Waves,
  Wifi,
  Wine,
  X,
} from 'lucide-react-native'

// Type-only re-export — erased at build time.
export type { LucideIcon } from 'lucide-react-native'
